// Automatically generated by bindings.c. DO NOT EDIT.

#include <cameraserver/CameraServer.h>

#include "luadef.h"

LUAFUNC void CameraServer_startAutomaticCapture(void* _this) {
    ((frc::CameraServer*)_this)
        ->startAutomaticCapture();
}
