// Automatically generated by bindings.c. DO NOT EDIT.

#include <cameraserver/CameraServer.h>

#include "luadef.h"

LUAFUNC void StartAutomaticCapture() {
    frc::CameraServer::StartAutomaticCapture();
}
