// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Filesystem.h>

#include "luadef.h"

LUAFUNC const char* GetDeployDirectory() {
  return stdStringForLua(frc::filesystem::GetDeployDirectory());
}
