// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Joystick.h>

#include "luadef.h"

// Construct an instance of a joystick.
LUAFUNC void* Joystick_new(int port) {
    return new frc::Joystick(port);
}

LUAFUNC double Joystick_GetX(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetX();
    return (double)_result;
}

LUAFUNC double Joystick_GetY(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetY();
    return (double)_result;
}

LUAFUNC double Joystick_GetZ(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetZ();
    return (double)_result;
}

LUAFUNC double Joystick_GetTwist(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTwist();
    return (double)_result;
}

LUAFUNC double Joystick_GetThrottle(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetThrottle();
    return (double)_result;
}

LUAFUNC bool Joystick_GetTriggerHeld(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTrigger();
    return (bool)_result;
}

LUAFUNC bool Joystick_GetTriggerPressed(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTriggerPressed();
    return (bool)_result;
}

LUAFUNC bool Joystick_GetTriggerReleased(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTriggerReleased();
    return (bool)_result;
}

LUAFUNC bool Joystick_GetTopHeld(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTop();
    return (bool)_result;
}

LUAFUNC bool Joystick_GetTopPressed(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTopPressed();
    return (bool)_result;
}

LUAFUNC bool Joystick_GetTopReleased(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetTopReleased();
    return (bool)_result;
}

LUAFUNC double Joystick_GetMagnitude(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetMagnitude();
    return (double)_result;
}

LUAFUNC double Joystick_GetDirectionRadians(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetDirectionRadians();
    return (double)_result;
}

LUAFUNC double Joystick_GetDirectionDegrees(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetDirectionDegrees();
    return (double)_result;
}

LUAFUNC bool Joystick_GetButtonHeld(void* _this, int button) {
    auto _result = ((frc::Joystick*)_this)
        ->GetRawButton(button);
    return (bool)_result;
}

LUAFUNC bool Joystick_GetButtonPressed(void* _this, int button) {
    auto _result = ((frc::Joystick*)_this)
        ->GetRawButtonPressed(button);
    return (bool)_result;
}

LUAFUNC bool Joystick_GetButtonReleased(void* _this, int button) {
    auto _result = ((frc::Joystick*)_this)
        ->GetRawButtonReleased(button);
    return (bool)_result;
}

LUAFUNC double Joystick_GetRawAxis(void* _this, int axis) {
    auto _result = ((frc::Joystick*)_this)
        ->GetRawAxis(axis);
    return (double)_result;
}

LUAFUNC int Joystick_GetPOV(void* _this, int port) {
    auto _result = ((frc::Joystick*)_this)
        ->GetPOV(port);
    return (int)_result;
}

LUAFUNC int Joystick_GetAxisCount(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetAxisCount();
    return (int)_result;
}

LUAFUNC int Joystick_GetPOVCount(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetPOVCount();
    return (int)_result;
}

LUAFUNC int Joystick_GetButtonCount(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetButtonCount();
    return (int)_result;
}

LUAFUNC bool Joystick_IsConnected(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->IsConnected();
    return (bool)_result;
}

LUAFUNC int Joystick_GetPort(void* _this) {
    auto _result = ((frc::Joystick*)_this)
        ->GetPort();
    return (int)_result;
}
