// Automatically generated by bindings.c. DO NOT EDIT.

#include <cassert>
#include <frc/drive/DifferentialDrive.h>
#include <frc/motorcontrol/MotorController.h>
#include <units/time.h>

#include "luadef.h"

LUAFUNC void* DifferentialDrive_new(void* leftMotor, void* rightMotor) {

      assert(leftMotor);
      assert(rightMotor);
      auto l = (frc::MotorController*)leftMotor;
      auto r = (frc::MotorController*)rightMotor;
      return new frc::DifferentialDrive(*l, *r);
    
}

LUAFUNC void DifferentialDrive_ArcadeDrive(void* _this, double xSpeed, double zRotation, bool squareInputs) {
    ((frc::DifferentialDrive*)_this)
        ->ArcadeDrive(xSpeed, zRotation, squareInputs);
}
