// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/RobotBase.h>

#include "luadef.h"

LUAFUNC bool RobotBase_IsEnabled(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsEnabled();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsDisabled(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsDisabled();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsAutonomous(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsAutonomous();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsAutonomousEnabled(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsAutonomousEnabled();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsTeleop(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsTeleop();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsTeleopEnabled(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsTeleopEnabled();
    return (bool)_result;
}

LUAFUNC bool RobotBase_IsTest(void* _this) {
    auto _result = ((frc::RobotBase*)_this)
        ->IsTest();
    return (bool)_result;
}

LUAFUNC int GetRuntimeType() {
    auto _result = frc::RobotBase::GetRuntimeType();
    return (int)_result;
}

LUAFUNC bool IsReal() {
    auto _result = frc::RobotBase::IsReal();
    return (bool)_result;
}

LUAFUNC bool IsSimulation() {
    auto _result = frc::RobotBase::IsSimulation();
    return (bool)_result;
}
