// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Timer.h>

#include "luadef.h"

LUAFUNC double GetFPGATimestamp() {
    return (double)frc::Timer::GetFPGATimestamp();
  
}
