// Automatically generated by bindings.c. DO NOT EDIT.

#include <units/time.h>
#include <frc/Timer.h>

#include "luadef.h"

LUAFUNC void new() {
    ::new();
}

LUAFUNC double Get() {
    auto _result = ::Get();
    return (double)_result;
}

LUAFUNC void Reset() {
    ::Reset();
}

LUAFUNC void Start() {
    ::Start();
}

LUAFUNC void Stop() {
    ::Stop();
}

LUAFUNC bool HasElapsed(double period) {
    auto _result = ::HasElapsed((uints::second_t)period);
    return (bool)_result;
}

LUAFUNC bool HasPeriodPassed(double period) {
    auto _result = ::HasPeriodPassed((uints::second_t)period);
    return (bool)_result;
}

LUAFUNC bool AdvanceIfElapsed(double period) {
    auto _result = ::AdvanceIfElapsed((uints::second_t)period);
    return (bool)_result;
}

LUAFUNC double GetFPGATimestamp() {
    auto _result = ::GetFPGATimestamp();
    return (double)_result;
}

LUAFUNC double GetMatchTime() {
    auto _result = ::GetMatchTime();
    return (double)_result;
}
