// Automatically generated by bindings.c. DO NOT EDIT.

#include <units/time.h>
#include <frc/Timer.h>

#include "luadef.h"

LUAFUNC void* Timer_new() {
    return new frc::Timer();
}

LUAFUNC double Timer_Get(void* _this) {
    auto _result = ((frc::Timer*)_this)
        ->Get();
    return (double)_result;
}

LUAFUNC void Timer_Reset(void* _this) {
    ((frc::Timer*)_this)
        ->Reset();
}

LUAFUNC void Timer_Start(void* _this) {
    ((frc::Timer*)_this)
        ->Start();
}

LUAFUNC void Timer_Stop(void* _this) {
    ((frc::Timer*)_this)
        ->Stop();
}

LUAFUNC bool Timer_HasElapsed(void* _this, double period) {
    auto _result = ((frc::Timer*)_this)
        ->HasElapsed((units::second_t)period);
    return (bool)_result;
}

LUAFUNC bool Timer_AdvanceIfElapsed(void* _this, double period) {
    auto _result = ((frc::Timer*)_this)
        ->AdvanceIfElapsed((units::second_t)period);
    return (bool)_result;
}

LUAFUNC double GetFPGATimestamp() {
    auto _result = frc::Timer::GetFPGATimestamp();
    return (double)_result;
}

LUAFUNC double GetMatchTime() {
    auto _result = frc::Timer::GetMatchTime();
    return (double)_result;
}
