-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class AHRS
---@field _this AHRS
AHRS = {}

---@param value integer
---@return any
function AHRS:new(value)
    value = AssertInt(value)
    local instance = {
        _this = ffi.C.AHRS_new(value),
    }
    setmetatable(instance, self)
    self.__index = self
    return instance
end

---@return number
function AHRS:getPitch()
    return ffi.C.AHRS_GetPitch(self._this)
end

---@return number
function AHRS:getRoll()
    return ffi.C.AHRS_GetRoll(self._this)
end

---@return number
function AHRS:getYaw()
    return ffi.C.AHRS_GetYaw(self._this)
end

---@return number
function AHRS:getCompassHeading()
    return ffi.C.AHRS_GetCompassHeading(self._this)
end

---@return any
function AHRS:zeroYaw()
    ffi.C.AHRS_ZeroYaw(self._this)
end

---@return boolean
function AHRS:isCalibrating()
    return ffi.C.AHRS_IsCalibrating(self._this)
end

---@return boolean
function AHRS:isConnected()
    return ffi.C.AHRS_IsConnected(self._this)
end

---@return number
function AHRS:getByteCount()
    return ffi.C.AHRS_GetByteCount(self._this)
end

---@return number
function AHRS:getUpdateCount()
    return ffi.C.AHRS_GetUpdateCount(self._this)
end

---@return number
function AHRS:getWorldLinearAccelX()
    return ffi.C.AHRS_GetWorldLinearAccelX(self._this)
end

---@return number
function AHRS:getWorldLinearAccelY()
    return ffi.C.AHRS_GetWorldLinearAccelY(self._this)
end

---@return number
function AHRS:getWorldLinearAccelZ()
    return ffi.C.AHRS_GetWorldLinearAccelZ(self._this)
end

---@return boolean
function AHRS:isMoving()
    return ffi.C.AHRS_IsMoving(self._this)
end

---@return boolean
function AHRS:isRotating()
    return ffi.C.AHRS_IsRotating(self._this)
end

---@return number
function AHRS:getBarometricPressure()
    return ffi.C.AHRS_GetBarometricPressure(self._this)
end

---@return number
function AHRS:getAltitude()
    return ffi.C.AHRS_GetAltitude(self._this)
end

---@return boolean
function AHRS:isAltitudeValid()
    return ffi.C.AHRS_IsAltitudeValid(self._this)
end

---@return boolean
function AHRS:getFusedHeading()
    return ffi.C.AHRS_GetFusedHeading(self._this)
end

---@return boolean
function AHRS:isMagneticDisturbance()
    return ffi.C.AHRS_IsMagneticDisturbance(self._this)
end

---@return boolean
function AHRS:isMagnetometerCalibrated()
    return ffi.C.AHRS_IsMagnetometerCalibrated(self._this)
end

---@return number
function AHRS:getQuaternionW()
    return ffi.C.AHRS_GetQuaternionW(self._this)
end

---@return number
function AHRS:getQuaternionX()
    return ffi.C.AHRS_GetQuaternionX(self._this)
end

---@return number
function AHRS:getQuaternionY()
    return ffi.C.AHRS_GetQuaternionY(self._this)
end

---@return number
function AHRS:getQuaternionZ()
    return ffi.C.AHRS_GetQuaternionZ(self._this)
end

---@return any
function AHRS:resetDisplacement()
    ffi.C.AHRS_ResetDisplacement(self._this)
end

---@param accel_x_g number
---@param accel_y_g number
---@param update_rate_hz integer
---@param is_moving boolean
---@return any
function AHRS:updateDisplacement(accel_x_g, accel_y_g, update_rate_hz, is_moving)
    accel_x_g = AssertNumber(accel_x_g)
    accel_y_g = AssertNumber(accel_y_g)
    update_rate_hz = AssertInt(update_rate_hz)
    ffi.C.AHRS_UpdateDisplacement(self._this, accel_x_g, accel_y_g, update_rate_hz, is_moving)
end

---@return number
function AHRS:getVelocityX()
    return ffi.C.AHRS_GetVelocityX(self._this)
end

---@return number
function AHRS:getVelocityY()
    return ffi.C.AHRS_GetVelocityY(self._this)
end

---@return number
function AHRS:getVelocityZ()
    return ffi.C.AHRS_GetVelocityZ(self._this)
end

---@return number
function AHRS:getDisplacementX()
    return ffi.C.AHRS_GetDisplacementX(self._this)
end

---@return number
function AHRS:getDisplacementY()
    return ffi.C.AHRS_GetDisplacementY(self._this)
end

---@return number
function AHRS:getDisplacementZ()
    return ffi.C.AHRS_GetDisplacementZ(self._this)
end

---@return number
function AHRS:getAngle()
    return ffi.C.AHRS_GetAngle(self._this)
end

---@return number
function AHRS:getRate()
    return ffi.C.AHRS_GetRate(self._this)
end

---@param angle number
---@return any
function AHRS:setAngleAdjustment(angle)
    angle = AssertNumber(angle)
    ffi.C.AHRS_SetAngleAdjustment(self._this, angle)
end

---@return number
function AHRS:getAngleAdjustment()
    return ffi.C.AHRS_GetAngleAdjustment(self._this)
end

---@return any
function AHRS:reset()
    ffi.C.AHRS_Reset(self._this)
end

---@return number
function AHRS:getRawGyroX()
    return ffi.C.AHRS_GetRawGyroX(self._this)
end

---@return number
function AHRS:getRawGyroY()
    return ffi.C.AHRS_GetRawGyroY(self._this)
end

---@return number
function AHRS:getRawAccelX()
    return ffi.C.AHRS_GetRawAccelX(self._this)
end

---@return number
function AHRS:getRawAccelY()
    return ffi.C.AHRS_GetRawAccelY(self._this)
end

---@return number
function AHRS:getRawAccelZ()
    return ffi.C.AHRS_GetRawAccelZ(self._this)
end

---@return number
function AHRS:getRawMagX()
    return ffi.C.AHRS_GetRawMagX(self._this)
end

---@return number
function AHRS:getRawMagY()
    return ffi.C.AHRS_GetRawMagY(self._this)
end

---@return number
function AHRS:getRawMagZ()
    return ffi.C.AHRS_GetRawMagZ(self._this)
end

---@return number
function AHRS:getPressure()
    return ffi.C.AHRS_GetPressure(self._this)
end

---@return number
function AHRS:getTempC()
    return ffi.C.AHRS_GetTempC(self._this)
end

---@return integer
function AHRS:getActualUpdateRate()
    return ffi.C.AHRS_GetActualUpdateRate(self._this)
end

---@param enable boolean
---@return any
function AHRS:enableLogging(enable)
    ffi.C.AHRS_EnableLogging(self._this, enable)
end

---@param enable boolean
---@return any
function AHRS:enableBoardlevelYawReset(enable)
    ffi.C.AHRS_EnableBoardlevelYawReset(self._this, enable)
end

---@return boolean
function AHRS:isBoardlevelYawResetEnabled()
    return ffi.C.AHRS_IsBoardlevelYawResetEnabled(self._this)
end

---@return integer
function AHRS:getGyroFullScaleRangeDPS()
    return ffi.C.AHRS_GetGyroFullScaleRangeDPS(self._this)
end

---@return integer
function AHRS:getAccelFullScaleRangeG()
    return ffi.C.AHRS_GetAccelFullScaleRangeG(self._this)
end

---@return any
function AHRS:calibrate()
    ffi.C.AHRS_Calibrate(self._this)
end
