-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class AHRS
---@field _this AHRS
AHRS = {}

---@param value integer
---@return any
function AHRS:new(value)
    value = AssertInt(value)
    local instance = {
        _this = ffi.C.AHRS_new(value),
    }
    setmetatable(instance, self)
    self.__index = self
    return instance
end

---@return number
function AHRS:getPitch()
    return ffi.C.AHRS_GetPitch(self._this)
end

---@return number
function AHRS:getAngle()
    return ffi.C.AHRS_GetAngle(self._this)
end

---@return any
function AHRS:reset()
    ffi.C.AHRS_Reset(self._this)
end
