-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class Joystick
---@field _this Joystick
Joystick = {}

---@class XboxButton
---@field A integer
---@field B integer
---@field X integer
---@field Y integer
---@field LeftBumper integer
---@field RightBumper integer
---@field Select integer
---@field Start integer
---@field LeftStick integer
---@field RightStick integer
XboxButton = BindingEnum:new('XboxButton', {
    A = 1,
    B = 2,
    X = 3,
    Y = 4,
    LeftBumper = 5,
    RightBumper = 6,
    Select = 7,
    Start = 8,
    LeftStick = 9,
    RightStick = 10,
})

-- Construct an instance of a joystick.
---@param port integer
---@return any
function Joystick:new(port)
    port = AssertInt(port)
    local instance = {
        _this = ffi.C.Joystick_new(port),
    }
    setmetatable(instance, self)
    self.__index = self
    return instance
end




---@return number
function Joystick:getTwist()
    return ffi.C.Joystick_GetTwist(self._this)
end


---@return boolean
function Joystick:getTriggerHeld()
    return ffi.C.Joystick_GetTriggerHeld(self._this)
end

---@return boolean
function Joystick:getTriggerPressed()
    return ffi.C.Joystick_GetTriggerPressed(self._this)
end

---@return boolean
function Joystick:getTriggerReleased()
    return ffi.C.Joystick_GetTriggerReleased(self._this)
end

---@return boolean
function Joystick:getTopHeld()
    return ffi.C.Joystick_GetTopHeld(self._this)
end

---@return boolean
function Joystick:getTopPressed()
    return ffi.C.Joystick_GetTopPressed(self._this)
end

---@return boolean
function Joystick:getTopReleased()
    return ffi.C.Joystick_GetTopReleased(self._this)
end

---@return number
function Joystick:getMagnitude()
    return ffi.C.Joystick_GetMagnitude(self._this)
end

---@return number
function Joystick:getDirectionRadians()
    return ffi.C.Joystick_GetDirectionRadians(self._this)
end

---@return number
function Joystick:getDirectionDegrees()
    return ffi.C.Joystick_GetDirectionDegrees(self._this)
end

---@param button integer
---@return boolean
function Joystick:getButtonHeld(button)
    button = AssertEnumValue(XboxButton, button)
    button = AssertInt(button)
    return ffi.C.Joystick_GetButtonHeld(self._this, button)
end

---@param button integer
---@return boolean
function Joystick:getButtonPressed(button)
    button = AssertEnumValue(XboxButton, button)
    button = AssertInt(button)
    return ffi.C.Joystick_GetButtonPressed(self._this, button)
end

---@param button integer
---@return boolean
function Joystick:getButtonReleased(button)
    button = AssertEnumValue(XboxButton, button)
    button = AssertInt(button)
    return ffi.C.Joystick_GetButtonReleased(self._this, button)
end


---@param port? integer
---@return integer
function Joystick:getPOV(port)
    port = port or 0
    port = AssertInt(port)
    return ffi.C.Joystick_GetPOV(self._this, port)
end

---@return integer
function Joystick:getAxisCount()
    return ffi.C.Joystick_GetAxisCount(self._this)
end

---@return integer
function Joystick:getPOVCount()
    return ffi.C.Joystick_GetPOVCount(self._this)
end

---@return integer
function Joystick:getButtonCount()
    return ffi.C.Joystick_GetButtonCount(self._this)
end

---@return boolean
function Joystick:isConnected()
    return ffi.C.Joystick_IsConnected(self._this)
end

---@return integer
function Joystick:getPort()
    return ffi.C.Joystick_GetPort(self._this)
end
