-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class RobotBase
---@field _this RobotBase
RobotBase = {}

---@return boolean
function RobotBase:isEnabled()
    return ffi.C.RobotBase_IsEnabled(self._this)
end

---@return boolean
function RobotBase:isDisabled()
    return ffi.C.RobotBase_IsDisabled(self._this)
end

---@return boolean
function RobotBase:isAutonomous()
    return ffi.C.RobotBase_IsAutonomous(self._this)
end

---@return boolean
function RobotBase:isAutonomousEnabled()
    return ffi.C.RobotBase_IsAutonomousEnabled(self._this)
end

---@return boolean
function RobotBase:isTeleop()
    return ffi.C.RobotBase_IsTeleop(self._this)
end

---@return boolean
function RobotBase:isTeleopEnabled()
    return ffi.C.RobotBase_IsTeleopEnabled(self._this)
end

---@return boolean
function RobotBase:isTest()
    return ffi.C.RobotBase_IsTest(self._this)
end

---@return integer
function getRuntimeType()
    return ffi.C.GetRuntimeType()
end

---@return boolean
function isReal()
    return ffi.C.IsReal()
end

---@return boolean
function isSimulation()
    return ffi.C.IsSimulation()
end
