-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@return boolean
function robotIsReal()
    return ffi.C.RobotIsReal()
end
