-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@return number
function getFPGATimestamp()
    return ffi.C.GetFPGATimestamp()
end
